### ISSUE TITLE
USER STORY: First impressions

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#1]
As a **new user** the **website is clearly geared towards children aged 8 - 12 and sharing writing**, so that **I know what the website is about and that it is suitable for me.**

## Acceptance Criteria

When I am first taken to the website:

1. I am drawn to a clear title "Inspiring Young Writers aged 8 - 12"
2. A hero image shows children at laptops creating stories and poems
3. The platform name "Inspiring young writers" is clearly displayed on the left of the nav bar.
5. A short introduction tells me exactly what the platform is for.

## Tasks

- [x] Create base.html in the templates folder
- [x] Boiler plate and main structure to base.html with block content holder
- [x] Create header.html and footer.html extending into base.html
- [x] Create view code for landing page (Home app)
- [x] Create templates to render the landing page - index.html
- [x] Connect up URL for index.html
- [x] Extend base.html into index.html
- [x] Add and style hero image (base.html)
- [x] Add and style title
- [x] Add and style introduction
- [x] Check responsivity, accessibility and performance of the landing page
- [x] Complete manual testing for acceptance criteria
