### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#11]
As a **registered user** I can **use my pen-name and password to login to my account*,* so that **my account remains secure and only I can login**.

## Acceptance Criteria

1. I can navigate intuitively and easily to the login page
2. The design of the page is pleasing to the eye and doesn't distract
3. The title and clear instructions help me to navigate the login process
4. Clear labels indicate the information to be added to each input field
5. The button to login is clear
6. When entering the wrong information I am prompted and informed what needs to be entered
7. I receive a clear message to let me know I have successfully logged in
8.  On logging in I am redirected to the account_home page

## Tasks

- [x] Create form for logging in
- [x] Create view for login.html
- [x] Create login.html
- [x] Add form to login and style
- [x] Add to urls.py
- [x] Add to header
- [x] Add validation
- [x] Test validation
- [x] success message
- [x] Check responsivity, accessibility and performance of the login page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
