### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#12]
As a **signed-in user** I can **easily logout of my account**, so that **I can keep my account secure**.

## Acceptance Criteria

1. I can logout out easily and intuitively
2. I am given clear success feedback on logging out of my account
3. On logging out I am redirected to the home page

## Tasks

- [x] Create view for logout.html
- [x] Add to urls.py
- [x] Add to account_header
- [x] Add confirmation message
- [x] Add success message 
- [x] Check responsivity, accessibility and performance of the logout page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks complete and acceptance criteria met
