### ISSUE TITLE
USER STORY: Password reset

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#13]
As a **registered user (with the help of my parent)** I can **reset my password using a link sent to my parent's email**, so that **if I forget my password I can still login to my account**.

## Acceptance Criteria

1. The login page has a clear link for 'Forgotten Password'
2. Clicking on 'Forgotten Password' takes me to a 'Password reset' page where I can enter the email address linked to my account
3. On submitting I am taken to a success message
4. I also receive an email with a link to reset my password
5. Clicking on the link takes me to the platform and a form to reset my password
6. On reseting my password I receive a success message with a link to login

## Tasks

- [x] Research password reset with Django
- [x] Create folder password_reset
- [x] Create password_reset.html
- [x] Create password_reset_sent.html
- [x] Create password_reset_form.html
- [x] Create password_reset_complete.html
- [x] Pull base.html and add content and styling to all htmls created
- [x] Add urls to main urls.py
- [x] Update settings.py
- [x] Add forgotten password link to login.html
- [x] Check it all works in development
- [x] Check responsivity, accessibility and performance of the password reset pages
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks complete and acceptance criteria met.
