### ISSUE TITLE
USER STORY: Admin access to delete accounts

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#17]
As the **site admin** I can **remove accounts**, so that **I can prevent unsuitable users from accessing and using the platform**.

## Acceptance Criteria

1. As a site admin I can log in to the admin side of the site
2. I can click to bring up a list of all registered users
3. I can click to delete a selected user
4. I am asked to confirm this action before it will be carried out

## Tasks

- [x] Create an admin.py within the users app
- [x] Add the User model to admin.py
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Associated bug #72 fixed
All tasks completed and acceptance criteria met
