### ISSUE TITLE
USER STORY: Account home

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#19]
As a **signed-in user** **once logged in I am taken to a homepage for my account**, so that **I have access to all the registered user features and it is clear I am logged in to my account**.

## Acceptance Criteria

1. The top left of the nav bar lets me know I am signed in to my account with wording unique to me "Pen name's inspiring writing"
2. The navigation bar provides links to all the registered user features
3. It is easy and intuitive to navigate through the available features.
4. A clear title welcomes me to my account
5. There are clear buttons to take me straight to important areas of the site.
6. The page cannot be accessed unless logged in

## Tasks

- [x] Create specific account header
- [x] Add account_header to tailwind
- [x] Adjust base.html to pull in account header when logged in
- [x] Create account app
- [x] Create account_home.html
- [x] Add account_home.html to tailwind
- [x] Create view code for account_home.html
- [x] Add to urls.py
- [x] Only accessible if authorised
- [x] Add Title
- [x] Add button ready
- [x] Check responsivity, accessibility and performance of the landing page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Tasks completed and accessibility criteria met
