### ISSUE TITLE
USER STORY: Featured work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#2]
As a **new user** I can **read work written by another child**, so that **I am inspired to write and share my writing**.

## Acceptance Criteria

1. When first landing on the site I can read a piece of published writing from the platform.
2. The writing is displayed directly under the platform title and call to action, so that I don't miss it.
3. Only writing specifically chosen to be featured is displayed.
4. The writing is referenced under a heading 'This week's featured article:'.
5. The writing includes title, author, author's age and the writing.

## Tasks

- [x] Adjust view for the landing page to pull the instance of writing with featured set to True.
- [x] Pass featured writing to index.html
- [x] Adjust index.html to render the writing
- [x] Adjust styling of index.html
- [x] Check responsivity, accessibility and performance of the landing page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met
