### ISSUE TITLE
USER STORY: Contact accessible when logged in

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#23]
As the **parent of a signed-in user** I can **also contact the site admin when my child is logged in**, so that **there is always an easy to access way to contact the site admin**.

## Acceptance Criteria

1. I can easily navigate to the contact page when logged in
2. I do not need to add in my name or email address as this can be gained from my user data
3. A clear message explains this

## Tasks

- [x] Create account_contact.html
- [x] Add to tailwind configs
- [x] Create view to display account_contact.html
- [x] Add view to urls
- [x] Add url to account_header
- [x] Add code to view
- [x] Add content and styling to account_contact
- [x] Check responsivity, accessibility and performance of the page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Tasks complete and acceptance criteria met
