### ISSUE TITLE
USER STORY: My work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#24]
As a **signed-in user** I can **navigate to a page where all my work is listed by status**, so that **I can quickly view all my work and see its current status**.

## Acceptance Criteria

1. I can navigate to my work from the navigation bar
2. I can navigate to my work from a call to action button on my account home page
3. A title shows me that I am in the 'My Work' section of the platform
4. I am shown a list of all my saved work
5. The list is categorised by published work, work awaiting approval and drafts
6. There is a clear button that takes me to the create writing page
7. The page cannot be accessed unless logged in
8. Users cannot accidentally access someone else's work

## Tasks

- [x] Create my_work.html
- [x] Add my_work.html to tailwind
- [x] Create view code for my_work.html
- [x] Add to urls.py
- [x] Add url to account_header
- [x] Add url to account_home
- [x] View only accessible if logged in
- [x] View pulls instances of writing with author name same as user
- [x] View calls my_work.html passing in the instances of writing
- [x] Instances rendered in html separated into: published, awaiting approval and drafts
- [x] Instances rendered with details: title, date published/submitted/update for
- [x] Add button to take user to 'create'
- [x] Check responsivity, accessibility and performance of the landing page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptability criteria met

**Comment by GeorginaCarlisle** [comment]
Re open to improve view. The following is needed:
- Instructions at the top
- Hover feature for all title links
- Anchor link for work not meeting requirements

**Comment by GeorginaCarlisle** [comment]
Extra work completed.
