### ISSUE TITLE
USER STORY: Write and submit work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#26]
As a **signed-in user** I can **write and submit a piece of work with title**, so that **I can share my writing with others**.

## Acceptance Criteria

1. From the account home page there is a clear button I can click that will take me directly to a page for inputting new work
2. The design of the page is pleasing to the eye and doesn't distract
3. The title and placeholder text help me to navigate the process of submitting my work
4. The button to submit my work for publishing is clear
5. I am given feedback to ensure that I am filling in the form correctly
6. On clicking the submit button, I am asked to confirm that I would like to submit my work to be published. This includes a quick explanation of the process
7. I am given clear feedback to let me know I have successfully submitted my work to be published on the site
8. On submission I am redirected to the account_home page

## Tasks

- [x] Research how to add a confirmation step to the process of submitting the form
- [x] Create new app "writing"
- [x] Add app to settings.py
- [x] Create model for the writing table
- [x] Add any validators needed at model level
- [x] Create form for creating new writing
- [x] Create view code
- [x] Add view to urls.py. Including adding pathway into main urls
- [x] Add url to account_home
- [x] Create html page incl. code and adding to tailwind.config
- [x] Add option to save as draft of submit to publish
- [x] Add confirmation step for submit to publish
- [x] Check responsivity, accessibility and performance of the contact pages
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Tasks completed and acceptance criteria met.
