### ISSUE TITLE
USER STORY: Writing validation

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#27]
As a **signed-in user** **my writing is passed through validation tests before it is saved**, so that **any text that may cause harm is prevented from entering the platform**.

## Acceptance Criteria

1. An error message is raised when a swear word is entered in the pen-name field.
2. An error message is raised when a swear word is entered in the title field both during writing creation and editing.
3. An error message is raised when a swear word is entered in the body field both during writing creation and editing.

## Tasks

- [x] Research how to validate against profanity
- [x] Create a validation function that checks against a list of swear words
- [x] Apply validation to the pen name field in the NewUserForm
- [x] Apply validation to the title and body name fields in the CreateWritingForm
- [x] Manual testing of acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Attempted to use: profanity-filter and profanity-check

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
