### ISSUE TITLE
USER STORY: View my published work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#31]
As a **signed-in user** I can **view my published work**, so that **I can re-read my writing**.

## Acceptance Criteria

1. When in 'My Work' clicking on the title of a piece of writing listed under 'My Published Work' will take me to a view_work page
2. The design of the page is pleasing to the eye and doesn't distract
3. 'title', 'date published' and 'writing' all displayed and easy to read
4. A back button (x) to return to 'My Work'
5. There are two clear options - edit writing and delete writing. 
6. Clicking 'edit writing' takes me to the edit_writing page with a message unique to editing published work.
7. Clicking to 'delete' my writing passes all user story USER STORY #34 criteria.

## Tasks

- [x] Create view_writing_view
- [x] Add url path which includes writing_id
- [x] Add url to rendering of published work in 'my work'
- [x] View gets writing using writing_id and sends to html
- [x] Create view_writing.html
- [x] Add view_writing.html to Tailwind.configs
- [x] Add html, python and styling to html
- [x]  Check responsivity, accessibility and performance of the edit_writing page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
