### ISSUE TITLE
USER STORY: View and edit work pending approval

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#32]
As a **signed-in user** I can **view and edit any work pending approval**, so that **I can re-read and edit should I wish**.

## Acceptance Criteria

1. When in 'My Work' clicking on the title of a piece of writing listed under 'My Work Awaiting Approval' will take me to a view page
2. The design of the page is pleasing to the eye and doesn't distract
3. The view work page displays the 'title', 'date submitted', 'writing' and a message.
4. An x in the top right of the container takes me back to 'My Work'
5.  The view work page has two buttons 'edit writing' and 'delete writing'
6.  Clicking to 'edit writing' takes me into the edit view with a message specific to work pending approval.
7.  Editing my work passes all user story #33 criteria
8.   Clicking to 'delete' my writing passes all user story #34 criteria 

## TASKS

- [x] Add url to rendering of work pending approval work in 'my work'
- [x] Add details specific to work pending approval in info section of view work
- [x] Add a specific message into edit work, for when editing work pending approval
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
