### ISSUE TITLE
USER STORY: View and edit draft work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#33]
As a **signed-in user** I can **view and edit my draft work**, so that **I can continue building on my writing**.

## Acceptance Criteria

1. When in 'My Work' clicking on the title of a piece of writing listed under 'My Drafts' will take me to an edit page
2. The design of the page is pleasing to the eye and doesn't distract
3. The draft work is displayed in a form allowing me to edit the title and or the writing
4. The form title and introduction help me to navigate the process of editing my work
5. There are three clear options - save draft, submit for publishing, delete writing
6. Save draft and submit for publishing function as per user stories #26 and #30
7.  Delete writing as per user story #34 
8.  An x in the top right of the container takes me back to 'My Work'
9. On clicking the x I am asked to confirm that there are no changes I wish to save

## Tasks

- [x] Create edit_writing.html
- [x] Create edit_writing_view
- [x] Add url path which includes writing_id
- [x] Add url to rendering of draft work in 'my work'
- [x] View gets writing using writing_id
- [x] View gets create writing form and populates with writing
- [x] View sends form to html
- [x] On form submission view checks submit button pressed and handles the form appropriately (use work in create_writing_view)
- [x] Add html, python and styling to html
- [x] Add x to go back
- [x]  Check responsivity, accessibility and performance of the edit_writing page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
