### ISSUE TITLE
USER STORY: Delete writing

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#34]
As a **signed-in user** I can **delete my writing**, so that **I can remove any of my writing that is saved on the platform should I wish**.

## Acceptance Criteria

1. Delete is an option I can access when editing or viewing my writing
2. I am reminded that once deleted I cannot get my writing back
3. I can confirm to delete or choose to keep
4. On choosing to delete my writing is deleted and I am returned to 'My work' with a success message
5. On choosing to keep I am return to editing or viewing my writing

## Tasks

- [x] Check delete functionality from "Edit Writing"
- [x] Create delete_writing_view
- [x] Add url path which includes writing_id
- [x] Add url to delete button in view writing
- [x] View code passes back a confirmation request to view_writing.html
- [x] Update view_writing.html to respond to request.
- [x] Update view to handle confirmation and delete writing
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptability criteria met
