### ISSUE TITLE
USER STORY: Admin approval of work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#35]
As the **site admin** **all work needs to be approved by me before it is published to the platform**, so that **I can ensure no inappropriate material is posted to the site**.

## Acceptance Criteria

1. I can view all instances of writing through the admin page
2. I can filter writing by pending_approval
3. I can read the title, body and author of each instance of writing
4. I can checkbox to change approved to True (default is False) and input the date
5. Only writing with approved True will be displayed in the library
6. I can also checkbox to change featured to True (default is false)
7. Only writing with approved True and featured True will be displayed on the landing page for all visitors to read

## Tasks
- [x] Create admin.py in the writing app
- [x] Create a class 'WritingAdmin' and add fields to be displayed, edited and filtered
- [x] Register the 'Writing' model and the 'WritingAdmin' class to the admin site
- [x] Manual testing acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
