### ISSUE TITLE
USER STORY: Email parents to inform of failed submission

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#38]
As the **site admin** I can **send parents an email sharing the submitted story and the reason why it failed to meet approval**, so that **I can keep parents informed and provide them with the information needed to support their child to keep other users on the site safe**.

## Acceptance Criteria

1. As site Admin I can handle this manually
2. When failing a submission I can see the author name for the writing being failed
3. I can locate the details for the author and find the information I need: email, first_name and last_name of parent/guardian.

## Tasks

- [x] Check that the field author is viewable in the writing section of the Admin page
- [x] Check that the fields email, first_name and last_name are viewable in the user section of the Admin page
- [x] Manual testing of acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met.
