### ISSUE TITLE
USER STORY: Parent information

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#4]
As the **parent of a new user** I am **provided with information which details how the platform works, the steps in place to protect my child and what me and my child can do to increase safety**, so that **I am fully aware of how the platform works**.

## Acceptance Criteria

1. I can navigate to 'Information for parents' from the navigation bar
2. I can navigate to 'Information for parents' from the sign-up page
3. 'Information for parents' opens up in a modal
4. A title makes it clear the information is targeted towards parents
5. An introduction quickly explains what information is contained in this section
6. The information is split into clear sections each with a title and picture
7. The layout and styling of the information makes it easy to scan and pick out information of interest.
8. A clear back button can be used to re-hide the information

## Tasks

- [x] Create parent_info.html in the main templates folder
- [x] Add to tailwind configs
- [x] Add basic modal layout to parent_info
- [x] Add Javascript to show parent_info modal when link in nav or link in sign-up form clicked.
- [x] Edit link in nav and link in sign-up form
- [x] Add Javascript to hide modal when x clicked
- [x] Pull parent_info into index.html, contact.html and sign-up.html
- [x] Add content and styling to parent_info
- [x] Check responsivity, accessibility and performance of the modal
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Re-opened in order to add information about feedback

**Comment by GeorginaCarlisle** [comment]
Feedback section added
