### ISSUE TITLE
USER STORY: View other users published work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#40]
As a **signed-in user** I can **view published work from other users**, so that **I can gain inspiration and tips for my own writing**.

## Acceptance Criteria

1. I can navigate to the library of inspiration from the navigation bar
2. I can navigate to the library from a call to action button on my account home page
3. The design of the page is pleasing to the eye and doesn't distract
4.  A title shows me that I am in the 'Library of inspiration' section of the platform
5.  I am shown a list of all published work
6.  For each piece of work I can read the 'title', 'author', 'age of author' and 'date published'
7.  The list is ordered by most recent first
8. Clicking on the title brings the writing up so that I can read it
9. In the read view I can click an x to take me back to the library

## Tasks

- [x] Create library app
- [x] Add app to settings.py
- [x] Create library.html
- [x] Create library_title.html
- [x] Create read.html
- [x] Add library.html, read.html and library_title.html to tailwind
- [x] Create view code for viewing library
- [x] Add to urls.py
- [x] Add to main urls.py
- [x] Add url to account_header (don't forget mobile nav)
- [x] Add url to account_home
- [x] View only accessible if logged in
- [x] View pulls all approved instances of writing
- [x] View renders library.html passing in the instances of writing
- [x] Add content and styling to library_title.html (title and instruction)
- [x] Pull base.html and library_title.html into library.html
- [x] Instances rendered in library.html with details: title, author, age and date published
- [x] Create view code for reading work
- [x] Add to urls.py
- [x] Add url to library
- [x] Add content and styling to read.html
- [x] Check responsivity, accessibility and performance of the library page
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptability criteria met
