### ISSUE TITLE
USER STORY: Contact

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#5]
As the **parent of a new user** I can **contact the site Admin**, so that **I can raise any concerns or ask any questions about the platform**.

## Acceptance Criteria

1. I can navigate intuitively and easily to the contact page
2. The design of the page is pleasing to the eye and doesn't distract
3. The title and introduction reassure me as to what the form is for
4. Clear labels indicate the information to be added to each input field
5. The button to submit is clear
6. When entering the wrong information I am prompted and informed what needs to be entered
7. I am given clear success feedback on submission of the form

## Tasks

- [x] Create contact.html (Home app)
- [x] Add view code for contact page 
- [x] Connect up URL for contact.html
- [x] Extend base.html into contact.html
- [x] Add form
- [x] Style form
- [x] Add success message
- [x] Check responsivity, accessibility and performance of the contact pages
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed, however manual testing failed on acceptance criteria 2 and 6. 
Additional bug (66) and task (67) added into the backlog.
User story to remain open until bug and task closed.

**Comment by GeorginaCarlisle** [comment]
Bug #66 and task #67 now completed.
