### ISSUE TITLE
USER STORY: Edit published work

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#53]
As a **signed-in user** I can **edit my published work**, so that **I can make changes in response to feedback should I wish**.

## Acceptance Criteria

1. When viewing my published work I can click a button to 'Edit writing'
2. Clicking to 'Edit writing' takes me to the Edit Writing page
3. I am given a message specific to editing published work
4. Editing my work passes all user story #33 criteria

## Tasks

- [x] Add link from view_writing to edit_writing
- [x] Add specific message to edit_writing for writing that has been approved
- [x] Manual testing of all acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met
