### ISSUE TITLE
USER STORY: Contact form data passed to Admin

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#6]
As the **site admin** I am **passed user's questions and concerns along with their contact details** so that **I can then respond**.

## Acceptance Criteria

1. Submitted contact us data emailed to the site owner

## Tasks

- [x] Research Django's send_email function
- [x] Pull data from the contact form into the backend
- [x] Pass the data into the send_email function
- [x] Add app to gmail account
- [x] Add settings to allow send_email function to work
- [x] Add additional config vars to Heroku
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
Acceptance criteria met
