### ISSUE TITLE
USER STORY: Developer Links

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#7]
As a **user** I am **provided with the name and contact links for the developer who created this platform** so that **rI know who created the platform and how to get in touch with them**.

## Acceptance Criteria

1. The name of the developer and year platform created are clearly visible at the bottom of every page.
2. On larger screens extra info is given to say that the platform was created for 'educational purposes only'.
3. Clear and easy to access links to take the user to the developer's LinkedIn and GitHub.
4. Clicking on links open relevant page in new tab.

## Tasks

- [x] Add html for the footer, developer name and nav links
- [x] Check links work
- [x] Add responsive styling
- [x] Check responsivity, accessibility and performance of the footer
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tested and acceptance criteria met.
