### ISSUE TITLE
USER STORY: Register

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/inspiring-young-writers#9]
As a **new user** I can **easily set up an account**, so that **I can access registered user only content and share my stories**.

## Acceptance Criteria

1.   I can navigate intuitively and easily to the sign-up page
2.  The landing page contains a call to action providing a direct and clear link to sign-up
3.  The design of the page is pleasing to the eye and doesn't distract
4.  The title and clear instructions help me to navigate the sign-up process
5.   It is clear which part of the form is for the child and which is for the parent
6.   Clear labels indicate the information to be added to each input field
7.   The button to sign-up is clear
8.   When entering the wrong information I am prompted and informed what needs to be entered
9.   I am given clear feedback to let me know I have successfully signed up
10.  On signing-up I am redirected to the account_home page.

## Tasks

- [x] Research customising authentication with Django
- [x] Create user model using Abstract Base User with  permissionsmixin
- [x] Include validator for age
- [x] Create base user manager
- [x] build create_user function
- [x] Update settings.py and migrate changes
- [x] create a form for registering
- [x] create a sign-up page
- [x] create a view for signing-up
- [x] add in urls for sign-up page
- [x] style and adjust html for sign-up page
- [x] Form validation and error handling
- [x] Change redirect to go to account home
- [x] success message
- [x] Check responsivity, accessibility and performance of the contact pages
- [x] Complete manual testing for acceptance criteria

**Comment by GeorginaCarlisle** [comment]
All tasks completed and acceptance criteria met. Additional tasks set up to make sign-up even better if time allows #70 and #71
